export const environment = {
  production: true,
  API_ENDPOINT: 'https://preapp.rayensalud.com/MiFamilia/Api/',
  URL_FOTOS: 'https://preapp.rayensalud.com/MiFamilia/',
  //API_ENDPOINT: 'https://app.rayensalud.com/MiFamilia/Api/',
  //URL_FOTOS: 'https://app.rayensalud.com/MiFamilia/',
  //API_ENDPOINT: 'http://192.168.0.153/MiFamilia.WebApi/Api/',
  //URL_FOTOS: 'http://192.168.0.153/MiFamilia.WebApi/',
  //API_ENDPOINT: 'http://190.151.14.104:1465/Api/',
  //URL_FOTOS: 'http://190.151.14.104:1465/',
  //API_ENDPOINT: 'http://localhost:27563/Api/',
  //URL_FOTOS: 'http://localhost:27563/',
  //API_ENDPOINT: 'http://192.168.0.169/MiFamilia.WebApi/Api/',
  //URL_FOTOS: 'http://192.168.0.169/MiFamilia.WebApi/',
  API_KEY_MAPA: 'AIzaSyAqx2BInVZJP-xhUh5oSUgKSPh3rpB_Rzc',
  USA_CALENDARIO: false,
  HORAS_FECHA_INICIO: 4,
  TIEMPO_CONSULTA_NOTIFICACIONES: 20000,
};
